language: erlang
env: DB=couchdb
services:
    - couchdb
otp_release:
   - R16B03-1
   - 17.0
   - 17.1
   - 18.0
   - 18.1
before_script:
  - curl -X PUT localhost:5984/couchbeam_testdb
  - curl -X PUT localhost:5984/couchbeam_testdb2
  - curl -X PUT localhost:5984/couchbeam_testdb3
  - "./support/bootstrap_travis.sh"
script: "./rebar3 eunit"
notifications:
  irc:
    - "irc.freenode.org#couchdbkit"
