Expm.Package.new(name: "couchbeam", description: "Apache CouchDB client in Erlang",
                 version: "1.0.3", keywords: ["couchdb",
                                              "http","client","binary",
                                              "database"],
                 dependencies: ["hackney"],
                 licenses: [[name: "MIT", file: "LICENSE"]],
                 contributors: [],
                 maintainers: [[name: "Benoit Chesneau",
                                email: "bchesneau@gmail.com"]],
                 repositories: [[github: "benoitc/couchbeam", tag: "1.0.3"]])
