IsRebar3 = erlang:function_exported(rebar3, main, 1),

Rebar2Deps = [
    {jsx, ".*", {git, "https://github.com/talentdeficit/jsx.git",
                 {tag,"2.8.0"}}},

    {hackney, ".*", {git, "https://github.com/benoitc/hackney.git",
                     {tag, "1.4.4"}}}
],

case IsRebar3 of
    true ->
        CONFIG;
    false ->
        CONFIG1 = lists:keyreplace(deps, 1, CONFIG, {deps, Rebar2Deps}),
        [{eunit_opts, [verbose]} | CONFIG1]
end.
