{application,couchbeam,
             [{description,"Erlang CouchDb kit"},
              {vsn,"0.1"},
              {modules,[couchbeam,
                        couchbeam_client,
                        couchbeam_mochijson2,
                        couchbeam_mochinum,
                        couchbeam_util,
                        couchbeam_sup]},
              {registered,[couchbeam_sup]},
              {applications,[kernel,stdlib,crypto]},
			  {env, []},
			  {mod, {couchbeam_app, []}}]}.